#!/usr/bin/env bash

echo "Checking for make..."
  if [ "$(which make)" == '' ]; then
	echo "You must have XCode CL tools (gcc, make etc) installed first"
	exit 1;
  fi

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing RVM (Ruby Version Manager) ..."
  curl -L https://get.rvm.io | bash -s stable --ruby
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.bashrc
  source ~/.bashrc
  source ~/.rvm/scripts/rvm

bash < <(curl -s https://raw.github.com/djburdick/laptop/master/ruby)

echo "Installing Homebrew, a good OS X package manager ..."
  ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.bashrc
  source ~/.bashrc

echo "Installing Mysql, open source DB"
  brew install mysql
  mysql_install_db --verbose --user=`whoami` --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql --tmpdir=/tmp

echo "Installing Redis, the badass key/value DB"
  brew install redis

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Install macvim for vimtasticness"
  brew install -v macvim --override-system-vim

echo "Install new ctags for code jumping in vim"
  brew install ctags

echo "Install vcprompt to show git branch info on commandline"
  mkdir ~/bin
  curl -sL https://github.com/djl/vcprompt/raw/master/bin/vcprompt > ~/bin/vcprompt
  chmod 755 ~/bin/vcprompt

bash < <(curl -s https://raw.github.com/djburdick/laptop/master/heroku)
